server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #本微服务为服务消费者，需要将自己注册到服务注册中心
    fetch-registry: true  #本微服务为服务消费者，需要到服务注册中心搜索服务

    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true #开启客户端 hystrix

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#
#logging:
#  level:
#    com.charles.springcloud.config.FeignOrderConfig: debug

